In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('mushrooms.csv')

In [3]:
df.head()

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0    p         x           s         n       t    p               f   
1    e         x           s         y       t    a               f   
2    e         b           s         w       t    l               f   
3    p         x           y         w       t    p               f   
4    e         x           s         g       f    n               f   

  gill_spacing gill_size gill_color  ... stalk_surface_below_ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring_number ring_type spore_print_color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [4]:
df.shape

(8124, 23)

#ENCODING THE CATEGORICAL DATA INTO NUMERICAL DATA

In [5]:
from sklearn.preprocessing import LabelEncoder 
from sklearn.model_selection import train_test_split

In [6]:
le=LabelEncoder()
ds=df.apply(le.fit_transform)
ds.head()

type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0     1          5            2          4        1     6                1   
1     0          5            2          9        1     0                1   
2     0          0            2          8        1     3                1   
3     1          5            3          8        1     6                1   
4     0          5            2          3        0     5                1   

   gill_spacing  gill_size  gill_color  ...  stalk_surface_below_ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk_color_above_ring  stalk_color_below_ring  veil_type  veil_color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring_number  ring_type  spore_print_color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [7]:
data=ds.values
print(data.shape)
print(type(data))
print(data[:5,:])

(8124, 23)
<class 'numpy.ndarray'>
[[1 5 2 4 1 6 1 0 1 4 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 9 1 0 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2 1]
 [0 0 2 8 1 3 1 0 0 5 0 2 2 2 7 7 0 2 1 4 3 2 3]
 [1 5 3 8 1 6 1 0 1 5 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 3 0 5 1 1 0 4 1 3 2 2 7 7 0 2 1 0 3 0 1]]


#SPILITTING THE DATA INTO TRAINING AND TESTING

In [8]:
x=data[:,1:]
y=data[:,0]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((6499, 22), (6499,), (1625, 22), (1625,))

In [9]:
np.unique(y_train)

array([0, 1])

 #MY NAIVE BAYES CLASSFIER CODE

In [10]:
def prior_prob(y_train,label):
    total_examples=y_train.shape[0]
    class_examples=np.sum(y_train==label)
    return (class_examples)/total_examples
def conditional_prob(x,y,col,col_val,label):
    x_=x[y==label]
    num=np.sum(x_[:,col]==col_val)
    deno=np.sum(y==label)
    return num/deno
def predict(x,y,test):
    labels=np.unique(y)
    posterior_prob=[]
    n=x.shape[1]
    for label in labels:
        likelyhood=1.0
        for i in range(n):
            cond=conditional_prob(x,y,i,test[i],label)
            likelyhood*=cond
        prior=prior_prob(y,label)
        post=likelyhood*prior
        posterior_prob.append(post)   
    max_index=np.argmax(posterior_prob)
    return labels[max_index]
    
     
     
    
    

In [11]:
output=predict(x_train,y_train,x_test[1])
print(output)

1


In [12]:
print(y_test[1])

1


#AS WE CAN SEE OUR CODE IS WORKING ABSOLUTELY FINE!

#CALCULATING THE SCORE

In [15]:
def score (x_train,y_train,x_test,y_test):
    pred=[]
    for i in range(x_test.shape[0]):
        pred_label=predict(x_train,y_train,x_test[i])
        pred.append(pred_label)
    pred=np.array(pred) 
    accuracy=np.sum(pred==y_test)/y_test.shape[0] 
    return accuracy

In [17]:
score(x_train,y_train,x_test,y_test)*100

99.75384615384615

##99.75 is the accuracy we are getting